# Generated by Django 3.2.12 on 2024-03-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='send_enquiry_mailer',
        ),
    ]
