# Generated by Django 3.2.12 on 2024-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_tourimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='images',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
