# Generated by Django 3.2.12 on 2024-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20240305_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='tour',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
