# Generated by Django 3.2.12 on 2024-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_auto_20240315_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
